apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}
